api_platform:
    mapping:
        paths: ['%kernel.project_dir%/modules']
    patch_formats:
        json:     ['application/merge-patch+json']
        jsonld:   ['application/ld+json']
        jsonapi:  ['application/vnd.api+json']
        html:     ['text/html']
        csv:      ['text/csv']
    swagger:
        versions: [3]
