old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
            read_write_timeout: 4
            heartbeat: 2
    producers:
        messaging:
            class: Modules\Product\Rabbit\ProductProducer
            connection:       default
            exchange_options: { name: 'q_product', type: direct }
    consumers:
        messaging:
            connection:       default
            exchange_options: { name: 'q_product', type: direct }
            queue_options:    { name: 'q_product'}
            callback:         Modules\Product\Rabbit\ProductConsumer
            enable_logger:    true
